Fix regression missed during history rewrite for GitHub

diff --git a/bin/autobuild b/bin/autobuild
--- a/bin/autobuild
+++ b/bin/autobuild
@@ -35,16 +35,21 @@ fi
 
 cd "$ZENV_CURRENT_WORK"
 
-# Fail if the user doesn't have the mac developer tools installed
-if [ "$(which clang)" == '' ]; then
-    echoerr 'You must have the Xcode command line tools installed to run the automatic builder.'
-    echoerr 'http://docwiki.embarcadero.com/RADStudio/XE4/en/Installing_the_Xcode_Command_Line_Tools_on_a_Mac'
-    exit 1
+PLATFORM=$(uname -a |grep -qi linux && echo 'linux' || echo 'osx');
+
+if [ $"{PLATFORM}" = 'osx' ]; then
+    # Fail if the user doesn't have the mac developer tools installed
+    if [ "$(which clang)" == '' ]; then
+        echoerr 'You must have the Xcode command line tools installed to run the automatic builder.'
+        echoerr 'http://docwiki.embarcadero.com/RADStudio/XE4/en/Installing_the_Xcode_Command_Line_Tools_on_a_Mac'
+        exit 1
+    fi
 fi
-# Automatically install MacFSEvents when you try to run this without it
-if [ "$(python -c 'import fsevents' 2>/dev/null; echo $?)" == '1' ]; then
-    echoerr 'You need to install MacFSEvents to use the automatic builder. If prompted, please type your sudo password below to install it.'
-    sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future easy_install macfsevents || exit 1
+
+# Automatically install watchdog when you try to run this without it
+if [ "$(python -c 'import watchdog' 2>/dev/null; echo $?)" == '1' ]; then
+    echoerr 'You need to install watchdog to use the automatic builder. If prompted, please type your sudo password below to install it.'
+    sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future easy_install watchdog || exit 1
     echo -e "---------------------------------------------------------\n"
 fi
 
