Add touch autobuilder support
git-svn-id: https://s.zoosk.com/zoosk-tools/trunk/zenv@108516 046000e8-c612-472f-bb51-fe359d1450d5

diff --git a/bin/autobuild b/bin/autobuild
--- a/bin/autobuild
+++ b/bin/autobuild
@@ -21,44 +21,84 @@ fi
 cd "$ZENV_CURRENT_WORK"
 
 REPO_TYPE=$(svn info | egrep --only-matching 'URL: .*' | sed 's|.*s\.zoosk\.com/\([^/]*\)/.*|\1|')
-if [ "$REPO_TYPE" != 'zoosk' -a "$REPO_TYPE" != 'zephyr_css' ]; then
-    echo 'Autobuild currently only works for Zoosk core and Zephyr checkouts.'
-    exit 1
+
+
+# Automatically install MacFSEvents when you try to run this without it
+if [ "$(python -c 'import fsevents' 2>/dev/null; echo $?)" == '1' ]; then
+    echo 'You need to install MacFSEvents to use the automatic builder. If prompted, please type your sudo password below to install it.'
+    sudo easy_install macfsevents || exit 1
+    echo -e "---------------------------------------------------------\n"
 fi
 
 
-if [ "$REPO_TYPE" == 'zoosk' ]; then
-    python "${ZENV_ROOT}/utils/autobuilder.py" &
-    WORKER_PID=$!
-    echo 'These directories are now being watched for changes:'
-    find "$ZENV_CURRENT_WORK" -name autobuild_settings | xargs -n 1 dirname
-    function quit() {
-        kill "$WORKER_PID"
-    }
-    trap quit EXIT
+case "$REPO_TYPE" in
+    'zoosk' )
+        python "${ZENV_ROOT}/utils/autobuilder.py" &
+        WORKER_PID=$!
+        echo 'These directories are now being watched for changes:'
+        find "$ZENV_CURRENT_WORK" -name autobuild_settings | xargs -n 1 dirname
+        function quit() {
+            kill "$WORKER_PID"
+        }
+        trap quit EXIT
+        ;;
 
-elif [ "$REPO_TYPE" == 'zephyr_css' ]; then
-    # The Zephyr build needs to use the SASS watcher to resolve dependencies, so we need to create its
-    # config using the regular build process if none exists
-    if [ ! -e 'build/config.rb' ]; then
-        ./zephyr compileSass
-    fi
-    compass watch -c build/config.rb &
-    COMPASS_PID=$!
-    python "${ZENV_ROOT}/utils/autobuilder.py" &
-    WORKER_PID=$!
-    function quit() {
-        kill -2 "$COMPASS_PID"
-        kill "$WORKER_PID"
-    }
-    trap quit EXIT
-    sleep 5
-    if [ "$(kill -0 $COMPASS_PID 2>/dev/null; echo $?)" != '0' ]; then
-        echo 'Compass failed to start. Make sure you have compass installed.'
+    'touch_js' )
+        # The Zephyr build needs to use the SASS watcher to resolve dependencies, so we need to create its
+        # config using the regular build process if none exists
+        if [ ! -e 'subprojects/css/build/config.rb' ]; then
+            echo 'No CSS files currently exist to update. Please run "build debugCss" or "build :css:compile" before running autobuild.'
+            exit 1
+        fi
+        python "${ZENV_ROOT}/utils/autobuilder.py" &
+        WORKER_PID=$!
+
+        cd subprojects/css
+        compass watch -c build/config.rb &
+        COMPASS_PID=$!
+        function quit() {
+            kill -2 "$COMPASS_PID"
+            kill "$WORKER_PID"
+        }
+        trap quit EXIT
+        sleep 5
+        if [ "$(kill -0 $COMPASS_PID 2>/dev/null; echo $?)" != '0' ]; then
+            echo 'Compass failed to start. Make sure you have compass installed.'
+            exit 1
+        fi
+        ;;
+
+    'zephyr_css' )
+        # The Zephyr build needs to use the SASS watcher to resolve dependencies, so we need to create its
+        # config using the regular build process if none exists
+        if [ ! -e 'build/config.rb' ]; then
+            echo 'No CSS files currently exist to update. Please run "build compileSass" or "./zephyr compileSass" before running autobuild.'
+            exit 1
+        fi
+        compass watch -c build/config.rb &
+        COMPASS_PID=$!
+        python "${ZENV_ROOT}/utils/autobuilder.py" &
+        WORKER_PID=$!
+        function quit() {
+            kill -2 "$COMPASS_PID"
+            kill "$WORKER_PID"
+        }
+        trap quit EXIT
+        sleep 5
+        if [ "$(kill -0 $COMPASS_PID 2>/dev/null; echo $?)" != '0' ]; then
+            echo 'Compass failed to start. Make sure you have compass installed. If you do not, run:'
+            echo 'sudo gem install --version 0.11.7 compass'
+            echo 'sudo gem install --version 0.9 compass-susy-plugin'
+            exit 1
+        fi
+        ;;
+
+    * )
+        echo "Autobuild is currently not supported for $REPO_TYPE checkouts."
         exit 1
-    fi
+        ;;
 
-fi
+esac
 
 
 echo 'Press enter or Ctrl+C to stop watching.'
