RC for Robin

diff --git a/bin/autobuild b/bin/autobuild
--- a/bin/autobuild
+++ b/bin/autobuild
@@ -21,20 +21,23 @@ fi
 cd "$ZENV_CURRENT_WORK"
 
 REPO_TYPE=$(inspect "$PWD" repo_type 2>/dev/null)
+PLATFORM=$(uname -a |grep -qi linux && echo 'linux' || echo 'osx');
 
-# # Fail if the user doesn't have the mac developer tools installed
-# if [ "$(which clang)" == '' ]; then
-#     echoerr 'You must have the Xcode command line tools installed to run the automatic builder.'
-#     echoerr 'http://docwiki.embarcadero.com/RADStudio/XE4/en/Installing_the_Xcode_Command_Line_Tools_on_a_Mac'
-#     exit 1
-# fi
-# # Automatically install MacFSEvents when you try to run this without it
-# if [ "$(python -c 'import fsevents' 2>/dev/null; echo $?)" == '1' ]; then
-#     echoerr 'You need to install MacFSEvents to use the automatic builder. If prompted, please type your sudo password below to install it.'
-#     sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future easy_install macfsevents || exit 1
-#     echo -e "---------------------------------------------------------\n"
-# fi
+if [ $"{PLATFORM}" = 'osx' ]; then
+    # Fail if the user doesn't have the mac developer tools installed
+    if [ "$(which clang)" == '' ]; then
+        echoerr 'You must have the Xcode command line tools installed to run the automatic builder.'
+        echoerr 'http://docwiki.embarcadero.com/RADStudio/XE4/en/Installing_the_Xcode_Command_Line_Tools_on_a_Mac'
+        exit 1
+    fi
+fi
 
+# Automatically install watchdog when you try to run this without it
+if [ "$(python -c 'import watchdog' 2>/dev/null; echo $?)" == '1' ]; then
+    echoerr 'You need to install watchdog to use the automatic builder. If prompted, please type your sudo password below to install it.'
+    sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future easy_install watchdog || exit 1
+    echo -e "---------------------------------------------------------\n"
+fi
 
 case "$REPO_TYPE" in
     'zoosk' )
@@ -47,7 +50,7 @@ case "$REPO_TYPE" in
         }
         trap quit EXIT
         ;;
-        
+
     'payment-service' )
         python "${ZENV_ROOT}/utils/autobuilder.py" &
         WORKER_PID=$!
@@ -58,7 +61,7 @@ case "$REPO_TYPE" in
         }
         trap quit EXIT
         ;;
-        
+
     'catalog-service' )
         python "${ZENV_ROOT}/utils/autobuilder.py" &
         WORKER_PID=$!
