RC for Robin

diff --git a/bin/notify b/bin/notify
--- a/bin/notify
+++ b/bin/notify
@@ -1,9 +1,21 @@
 #! /usr/bin/env bash
 
-## Bail on errors or unset vars
+## PURPOSE
+#
+# This is a wrapper script around desktop notifications.
+# It supports OSX and Linux (KDE/UNITY/GNOME), and should
+# be easily motified to work on other systems.
+#
+# PLEASE USE ONLY X-PLATFORM SUPPORTED OPTIONS for zenv scripts:
+# -title, -message, and -help.
+#
+# All other options are OSX specific.
+#
+
+## BAIL on errors
 set -e # we can not use set -u as we rely on XDG_CURRENT_DESKTOP
 
-# Startup checks
+## CHECK envrionment
 if [ -z "$ZENV_INITIALIZED" ]; then
     echo 'You must run this program from within ZEnv.'
     exit 1
@@ -11,7 +23,7 @@ fi
 
 NOTIFY_DE="${XDG_CURRENT_DESKTOP}"
 
-# Support OSX EXACTLY as before
+## Support OSX EXACTLY as before
 if [ -z "${NOTIFY_DE}" ]; then
     BIN_FILE="${ZENV_ROOT}"/utils/terminal-notifier.app/Contents/MacOS/terminal-notifier
     if [ -n "$1" -a "$(echo "$1" | sed 's/\(.\).*/\1/')" != '-' ]; then
@@ -22,93 +34,88 @@ if [ -z "${NOTIFY_DE}" ]; then
     exit $?
 fi
 
-# Other environments
+## SET script vars
 NOTIFY_TITLE=''; # Title
 NOTIFY_MSG='';   # Message
 NOTIFY_DWELL=2;  # Residency time
 ARG_STACK=();
 
-# Set title and message per options
+## BEGIN SET title and message per options
 while :; do
-  case $1 in
-    -h|--help|-\?)
-      echo "Notify is a zenv cross-platform wrapper for desktop notifications."
-      echo "Only -message and -title options are supported across all platforms."
-      exit 0;
-      ;;
+    case $1 in
+        -h|--help|-\?)
+           echo "Notify is a zenv cross-platform wrapper for desktop notifications."
+           echo "Only -message and -title options are supported across all platforms."
+           exit 0;
+           ;;
 
-    -title)
-      if [ "${2}" ]; then
-        NOTIFY_TITLE="${2}"
-        shift 2
-        continue
-      else
-        echo "Error, option ${1} requires an argument."
-        exit 1
-      fi
-      ;;
+        -title)
+            if [ "${2}" ]; then
+              NOTIFY_TITLE="${2}"
+              shift 2
+              continue
+            else
+              echo "Error, option ${1} requires an argument."
+              exit 1
+            fi
+            ;;
 
-    -message)
-      if [ "${2}" ]; then
-        NOTIFY_MSG="${2}"
-        shift 2
-        continue
-      else
-        echo "Error, option ${2} requires an argument."
-        exit 1
-      fi
-      ;;
+        -message)
+            if [ "${2}" ]; then
+              NOTIFY_MSG="${2}"
+              shift 2
+              continue
+            else
+              echo "Error, option ${2} requires an argument."
+              exit 1
+            fi
+            ;;
 
-    -dwell)
-      if [ "${2}" ]; then
-        let NOTIFY_DWELL="${2}"+0
-        shift 2
-        continue
-      else
-        echo "Error, option ${2} requires an argument."
-        exit 1
-      fi
-      ;;
+        -dwell)
+            if [ "${2}" ]; then
+              let NOTIFY_DWELL="${2}"+0
+              shift 2
+              continue
+            else
+              echo "Error, option ${2} requires an argument."
+              exit 1
+            fi
+            ;;
 
-    --) # end of all options
-      shift
-      break
-      ;;
-
-    *)
-      # If no options provided, use the first argument as the message
-      # and the second as the title.
-      if [ -z "${NOTIFY_MSG}" ] && [ -z "${NOTIFY_TITLE}" ]; then
-        NOTIFY_MSG="${1}"
-        if [ -z "${NOTIFY_MSG}" ]; then exit 0; fi
-      fi
-      break
-      ;;
-  esac
-  shift
+        # end of all options
+        --)
+            shift
+            break
+            ;;
+        # If no options provided, use the first argument as the message
+        # and the second as the title.
+        *)  
+            if [ -z "${NOTIFY_MSG}" ] && [ -z "${NOTIFY_TITLE}" ]; then
+              echo "$@"
+              NOTIFY_MSG="$@"
+              if [ -z "${NOTIFY_MSG}" ]; then exit 0; fi
+            fi
+            break
+            ;;
+    esac
+    shift
 done
+## END SET title and message per options
 
-
+## BEGIN RUN appropriate desktop command
 case "${NOTIFY_DE}" in
     KDE)
         if [ ! -z $(which kdialog) ]; then
-            ARG_STACK+=('--title')
-            ARG_STACK+=("${NOTIFY_TITLE:-...}")
-            ARG_STACK+=('--passivepopup')
-            ARG_STACK+=("${NOTIFY_MSG:-...}")
-            ARG_STACK+=("${NOTIFY_DWELL}")
-
-            kdialog ${ARG_STACK[*]}
+            kdialog --title "${NOTIFY_TITLE:-...}" --passivepopup \
+                "${NOTIFY_MSG:-...}" ${NOTIFY_DWELL:-2}
         fi
         ;;
     *) # Unity, Gnome, etc
         if [ ! -z $(which notify-send) ]; then
-            ARG_STACK+=("${NOTIFY_TITLE:-...}")
-            ARG_STACK+=("${NOTIFY_MSG:-...}")
-            ARG_STACK+=('-t')
-            ARG_STACK+=("${NOTIFY_DWELL}")
-
-            notify_send ${ARG_STACK[*]}
+            notify_send "${NOTIFY_TITLE:-...}"
+                "${NOTIFY_MSG:-...}" -t ${NOTIFY_DWELL:-2}
         fi
         ;;
 esac
+## END RUN appropriate desktop command
+
