ZEnv - Support building touch checkouts, auto-select a workspace, and random bugfixes
git-svn-id: https://s.zoosk.com/zoosk-tools/trunk/zenv@105006 046000e8-c612-472f-bb51-fe359d1450d5

diff --git a/bin/work_init b/bin/work_init
--- a/bin/work_init
+++ b/bin/work_init
@@ -13,9 +13,46 @@ if [ -z "$ZENV_INITIALIZED" ]; then
     exit 1
 fi
 
-if [ "$ZENV_CURRENT_WORK" != "" ]; then
-    cd "$ZENV_CURRENT_WORK"
-fi
+##
+# Update the zoosk core properties file.
+#
+function update_properties() {
+
+    if [ -e "$ZENV_BUILDPROPS" ]; then
+        read -p 'Would you like me to fill in some values in your properties file [y/n] (n)? ' TEMP
+        if [ "$TEMP" == 'y' ]; then
+            if [ $ZENV_DEVID -lt 10 ]; then
+                NUMBERPAD='0'
+            else
+                NUMBERPAD=''
+            fi
+            # TODO: Change .* to $ to only replace empty settings
+            sed -e "s/^devid=\$/devid=${ZENV_DEVID}/" \
+                -e "s/^dbprefix=\$/dbprefix=${NUMBERPAD}\${devid}/" \
+                -e "s/^memcache_port=\$/memcache_port=$(($ZENV_DEVID % 10))/" \
+                -e "s/^dev_hostip=\$/dev_hostip=$(host ${ZENV_DEVSERVER} | awk '{print $4}')/" \
+                -e "s/^dev_hostname=\$/dev_hostname=${ZENV_DEVSERVER}/" \
+                -e "s/^dev_serverid=\$/dev_serverid=${ZENV_SERVERID}/" \
+                -e "s/^dev_dbhostip=\$/dev_dbhostip=${ZENV_DBIP}/" \
+                -e "s/^dev_aws_secret_access_key=\$/dev_aws_secret_access_key=C7eDlLbtQ8fiIXseo69g3aeOXZf7QzsyxnpMTQWy/" \
+                -e "s/^dev_offerpal_api_secret=\$/dev_offerpal_api_secret=1830806557011586/" \
+                -e "s/^dev_rootdbpass=\$/dev_rootdbpass=nwN9vrsbzl@vdc4f/" \
+                -e "s/^dev_saftpay_api_secret=\$/dev_saftpay_api_secret=347ae91d1bac4d4a88760ca1d875b9cf/" \
+                -e "s/^dev_iovation_dra_password=\$/dev_iovation_dra_password=86TNJS89S/" \
+                -e "s/^dev_recatpcha_api_secret=\$/dev_recatpcha_api_secret=6Ld0CAQAAAAAALe6IDgE8F0skZAhNVg81EGO7Mni/" \
+                -e "s/^dev_syniverseftpusername=\$/dev_syniverseftpusername=pickuser/" \
+                -e "s/^dev_syniverseftppassword=\$/dev_syniverseftppassword=S\&F#T9P/" \
+                -e "s/^dev_test_email=\$/dev_test_email=$(whoami)@zoosk.com/" \
+                -e "s/^dev_tigasebuildno=\$/dev_tigasebuildno=0.0.0.0/" \
+                -e "s/^dev_chatbuildno=\$/dev_chatbuildno=0.0.0.\${devid}/" \
+                -e "s/^dev_chat_port=\$/dev_chat_port=6${NUMBERPAD}$(($ZENV_DEVID % 10))0/" \
+                -e "s/^dev_bosh_port=\$/dev_bosh_port=6${NUMBERPAD}$(($ZENV_DEVID % 10))2/" \
+                -e "s/^dev_bosh_ssl_port=\$/dev_bosh_ssl_port=6${NUMBERPAD}$(($ZENV_DEVID % 10))3/" \
+                -i '' "$ZENV_BUILDPROPS"
+        fi
+    fi
+}
+
 
 echo "Please answer some questions to set up ${PWD} as a workspace."
 
@@ -47,10 +84,39 @@ if [ "$TEMP" == 'y' ]; then
 fi
 
 ZENV_BUILDPROPS="${PWD}/dev.properties"
-read -p "Enter the path to your dev properties file if you have one (${ZENV_BUILDPROPS}): " TEMP
+read -p "Enter the path to your dev properties file (${ZENV_BUILDPROPS}): " TEMP
 if [ "$TEMP" != '' ]; then
     ZENV_BUILDPROPS="$TEMP"
 fi
+
+
+# Detect what kind of workspace we're in by using SVN
+if [ ! -e '.svn' ]; then
+    echo "This folder doesn't seem to be an SVN checkout of anything."
+    exit 1
+fi
+REPO_KIND=$(svn info | egrep --only-matching 'URL: .*' | sed 's|.*s\.zoosk\.com/\([^/]*\)/.*|\1|')
+
+# Add the correct build command based on the detected repo type
+DONE=0
+while [ $DONE -eq 0 ]; do
+    case "$REPO_KIND" in 
+        'zoosk' )
+            ZENV_BUILD_COMMAND="phing -logger phing.listener.DefaultLogger -Dpf1=\${ZENV_BUILDPROPS} -Dpf2=\${ZENV_CURRENT_WORK}/zooskdev.properties"
+            update_properties
+            DONE=1
+            ;;
+        'touch_js' )
+            ZENV_BUILD_COMMAND="./gradlew -Pproperties_file=\${ZENV_BUILDPROPS}"
+            DONE=1
+            ;;
+        * )
+            echo "Couldn't determine the checkout type. Please enter it manually."
+            echo 'The type should be the name of the svn directory, e.g. zoosk or touch_js.'
+            read -p '> ' REPO_KIND
+    esac
+done
+
 
 # Generate the setup file
 echo "#! /usr/bin/env bash
@@ -66,41 +132,12 @@ export ZENV_SERVERDIR=${ZENV_SERVERDIR}
 # The properties file used to build this workspace.
 export ZENV_BUILDPROPS=${ZENV_BUILDPROPS}
 
-" > work.properties
+# The command that will be used to build your code. Arguments are appended.
+export ZENV_BUILD_COMMAND=\"${ZENV_BUILD_COMMAND}\"
 
-if [ -e "$ZENV_BUILDPROPS" ]; then
-    read -p 'Would you like me to fill in some values in your properties file [y/n] (n)? ' TEMP
-    if [ "$TEMP" == 'y' ]; then
-        if [ $ZENV_DEVID -lt 10 ]; then
-            NUMBERPAD='0'
-        else
-            NUMBERPAD=''
-        fi
-        # TODO: Change .* to $ to only replace empty settings
-        sed -e "s/^devid=.*/devid=${ZENV_DEVID}/" \
-            -e "s/^dbprefix=.*/dbprefix=${NUMBERPAD}\${devid}/" \
-            -e "s/^memcache_port=.*/memcache_port=$(($ZENV_DEVID % 10))/" \
-            -e "s/^dev_hostip=.*/dev_hostip=$(host ${ZENV_DEVSERVER} | awk '{print $4}')/" \
-            -e "s/^dev_hostname=.*/dev_hostname=${ZENV_DEVSERVER}/" \
-            -e "s/^dev_serverid=.*/dev_serverid=${ZENV_SERVERID}/" \
-            -e "s/^dev_dbhostip=.*/dev_dbhostip=${ZENV_DBIP}/" \
-            -e "s/^dev_aws_secret_access_key=.*/dev_aws_secret_access_key=C7eDlLbtQ8fiIXseo69g3aeOXZf7QzsyxnpMTQWy/" \
-            -e "s/^dev_offerpal_api_secret=.*/dev_offerpal_api_secret=1830806557011586/" \
-            -e "s/^dev_rootdbpass=.*/dev_rootdbpass=nwN9vrsbzl@vdc4f/" \
-            -e "s/^dev_saftpay_api_secret=.*/dev_saftpay_api_secret=347ae91d1bac4d4a88760ca1d875b9cf/" \
-            -e "s/^dev_iovation_dra_password=.*/dev_iovation_dra_password=86TNJS89S/" \
-            -e "s/^dev_recatpcha_api_secret=.*/dev_recatpcha_api_secret=6Ld0CAQAAAAAALe6IDgE8F0skZAhNVg81EGO7Mni/" \
-            -e "s/^dev_syniverseftpusername=.*/dev_syniverseftpusername=pickuser/" \
-            -e "s/^dev_syniverseftppassword=.*/dev_syniverseftppassword=S\&F#T9P/" \
-            -e "s/^dev_test_email=.*/dev_test_email=$(whoami)@zoosk.com/" \
-            -e "s/^dev_tigasebuildno=.*/dev_tigasebuildno=0.0.0.0/" \
-            -e "s/^dev_chatbuildno=.*/dev_chatbuildno=0.0.0.\${devid}/" \
-            -e "s/^dev_chat_port=.*/dev_chat_port=6${NUMBERPAD}$(($ZENV_DEVID % 10))0/" \
-            -e "s/^dev_bosh_port=.*/dev_bosh_port=6${NUMBERPAD}$(($ZENV_DEVID % 10))2/" \
-            -e "s/^dev_bosh_ssl_port=.*/dev_bosh_ssl_port=6${NUMBERPAD}$(($ZENV_DEVID % 10))3/" \
-            -i '' "$ZENV_BUILDPROPS"
-    fi
-fi
+" > "$ZENV_WORKSPACE_SETTINGS"
+
 
 # Switch to the new workspace
+echo 'Your new workspace is ready to use.'
 use $(basename "$PWD")
